"""AddMore

Revision ID: 6c29128b8213
Revises: b9c2fdb143f1
Create Date: 2025-01-30 19:45:28.261964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c29128b8213'
down_revision: Union[str, None] = 'b9c2fdb143f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('severity', sa.String(), nullable=False))
    op.add_column('alerts', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'status')
    op.drop_column('alerts', 'severity')
    # ### end Alembic commands ###
